name: "build"
on:
  push:
    branches: [master]
    paths-ignore:
      - "*.md"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# concurrency:
#   group: ${{ github.ref }}
#   cancel-in-progress: true
# permissions:
#   contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]
        platform: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            rust_target: x86_64-pc-windows-msvc
          - os: macos-latest
            rust_target: x86_64-apple-darwin
          - os: macos-latest
            rust_target: aarch64-apple-darwin
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ env.GITHUB_TOKEN }}
      - name: Build the App (Linux)
        if: matrix.platform == 'ubuntu-latest'
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/zanzythebar/tauridocker:latest
          options: -v ${{ github.workspace }}:/workspace
          run: |
            echo "::install node dependencies"
            npm install
            echo "::tauri build"
            npm tauri build
      - name: Archive the App (Linux)
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: |
            src-tauri/target/release/bundle/deb/*.deb
            src-tauri/target/release/bundle/appimage/*.AppImage
          retention-days: 5
          if-no-files-found: error
      - name: Verify build (Linux)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          ls -la src-tauri/target/release/bundle/appimage
          ls -la src-tauri/target/release/bundle/deb

      - name: Node.js setup ${{ matrix.node-version }} (Windows & MacOS)
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies (Windows & MacOS)
        if: matrix.platform == 'windows-latest' || matrix.platform == 'macos-latest'
        run: |
            echo "::install node dependencies"
            npm install
            echo "::tauri build"
            npm tauri build

      - name: Setup Rust (Windows & MacOS)
        if: matrix.platform == 'windows-latest' || matrix.platform == 'macos-latest'
        uses: actions-rs/toolchain@v1
        with:
          default: true
          override: true
          profile: minimal
          toolchain: stable
          target: ${{ matrix.platform.rust_target }}

      - name: Cache Rust (Windows & MacOS)
        if: matrix.platform == 'windows-latest' || matrix.platform == 'macos-latest'
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Build the app (Windows & MacOS)
        if: matrix.platform == 'windows-latest' || matrix.platform == 'macos-latest'
        uses: JonasKruckenberg/tauri-build@v1.2.3
        id: tauri_build
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        with:
          target: ${{ matrix.platform.rust_target }}

      - name: Archive the App (Windows & MacOS)
        if: matrix.platform == 'windows-latest' || matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: "${{ join(fromJSON(steps.tauri_build.outputs.artifacts), '\n') }}"
          retention-days: 5
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create Directory
        run: mkdir -p dist
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Release
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        run: |
          sudo apt-get install -y jq
          chmod +x ./scripts/prepareCMD.sh
          semantic-release
